TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += st1Channel.boot
TARGETS += st2Channel.boot
TARGETS += st4Channel.boot
TARGETS += st4ChannelMini.boot
TARGETS += st6Channel.boot
TARGETS += st6ChannelMini.boot
TARGETS += st7Channel.boot
TARGETS += st8Channel.boot
TARGETS += st8ChannelMini.boot
TARGETS += st16Channel.boot
TARGETS += st16ChannelMini.boot
TARGETS += st32Channel.boot
include $(TOP)/configure/RULES.ioc
