# Load Default values for a single channel

dbpf("$(PREFIX)C$(CHAN)SCA:EnableCallbacks", "Enable")
dbpf("$(PREFIX)C$(CHAN)SCA0:AttrName", "CHAN$(CHAN)SCA0")
dbpf("$(PREFIX)C$(CHAN)SCA1:AttrName", "CHAN$(CHAN)SCA1")
dbpf("$(PREFIX)C$(CHAN)SCA2:AttrName", "CHAN$(CHAN)SCA2")
dbpf("$(PREFIX)C$(CHAN)SCA3:AttrName", "CHAN$(CHAN)SCA3")
dbpf("$(PREFIX)C$(CHAN)SCA4:AttrName", "CHAN$(CHAN)SCA4")
dbpf("$(PREFIX)C$(CHAN)SCA5:AttrName", "CHAN$(CHAN)SCA5")
dbpf("$(PREFIX)C$(CHAN)SCA6:AttrName", "CHAN$(CHAN)SCA6")
dbpf("$(PREFIX)C$(CHAN)SCA7:AttrName", "CHAN$(CHAN)SCA7")
dbpf("$(PREFIX)C$(CHAN)SCA8:AttrName", "CHAN$(CHAN)SCA8")

dbpf("$(PREFIX)ROI$(CHAN):EnableX", "Enable")
dbpf("$(PREFIX)ROI$(CHAN):EnableY", "Enable")
dbpf("$(PREFIX)ROI$(CHAN):EnableZ", "Disable")
dbpf("$(PREFIX)ROI$(CHAN):SizeY", "1")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableX", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableY", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):SizeY", "1")

dbpf("$(PREFIX)ROI$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCASUM$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN)ROI:EnableCallbacks", "Enable")

dbpf("$(PREFIX)MCA$(CHAN):ArrayData.LOPR", 0.5)

dbpf("$(PREFIX)C$(CHAN):DeadTime_RBV.SCAN", ".1 second")
dbpf("$(PREFIX)C$(CHAN):DTFactor_RBV.SCAN", ".1 second")

dbpf("$(PREFIX)MCA$(CHAN)ROI:1:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:2:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:3:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:4:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:5:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:6:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:7:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:8:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:9:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:10:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:11:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:12:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:13:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:14:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:15:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:16:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:17:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:18:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:19:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:20:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:21:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:22:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:23:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:24:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:25:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:26:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:27:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:28:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:29:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:30:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:31:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:32:Use", "Yes")
