#!/bin/sh
# This file was automatically generated on Fri 17 Feb 2017 16:03:58 GMT from
# source: /home/xspress3/xspress3/etc/makeIocs/xspress3.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi
exec ./xspress3App st2Channel.boot
