# Load Default values for a single channel

dbpf("$(PREFIX)C$(CHAN)SCA:EnableCallbacks", "Enable")

dbpf("$(PREFIX)C$(CHAN)SCA:0:AttrName", "CHAN$(CHAN)SCA0")
dbpf("$(PREFIX)C$(CHAN)SCA:1:AttrName", "CHAN$(CHAN)SCA1")
dbpf("$(PREFIX)C$(CHAN)SCA:2:AttrName", "CHAN$(CHAN)SCA2")
dbpf("$(PREFIX)C$(CHAN)SCA:3:AttrName", "CHAN$(CHAN)SCA3")
dbpf("$(PREFIX)C$(CHAN)SCA:4:AttrName", "CHAN$(CHAN)SCA4")
dbpf("$(PREFIX)C$(CHAN)SCA:5:AttrName", "CHAN$(CHAN)SCA5")
dbpf("$(PREFIX)C$(CHAN)SCA:6:AttrName", "CHAN$(CHAN)SCA6")
dbpf("$(PREFIX)C$(CHAN)SCA:7:AttrName", "CHAN$(CHAN)SCA7")
dbpf("$(PREFIX)C$(CHAN)SCA:8:AttrName", "CHAN$(CHAN)EventWidth")
dbpf("$(PREFIX)C$(CHAN)SCA:9:AttrName", "CHAN$(CHAN)DTFactor")
dbpf("$(PREFIX)C$(CHAN)SCA:10:AttrName", "CHAN$(CHAN)DTPercent")

dbpf("$(PREFIX)C$(CHAN)SCA:TS:0:Name", "CHAN$(CHAN)SCA0")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:1:Name", "CHAN$(CHAN)SCA1")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:2:Name", "CHAN$(CHAN)SCA2")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:3:Name", "CHAN$(CHAN)SCA3")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:4:Name", "CHAN$(CHAN)SCA4")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:5:Name", "CHAN$(CHAN)SCA5")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:6:Name", "CHAN$(CHAN)SCA6")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:7:Name", "CHAN$(CHAN)SCA7")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:8:Name", "CHAN$(CHAN)EventWidth")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:9:Name", "CHAN$(CHAN)DTFactor")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:10:Name", "CHAN$(CHAN)DTPercent")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:NDArrayAddress", "1")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:TSAcquireMode", "0")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:TSNumPoints", "$(NCHANS)")
dbpf("$(PREFIX)C$(CHAN)SCA:TS:TSRead.SCAN", ".5 second")

dbpf("$(PREFIX)ROI$(CHAN):EnableX", "Enable")
dbpf("$(PREFIX)ROI$(CHAN):EnableY", "Enable")
dbpf("$(PREFIX)ROI$(CHAN):EnableZ", "Disable")
dbpf("$(PREFIX)ROI$(CHAN):SizeY", "1")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableX", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableY", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):SizeY", "1")

dbpf("$(PREFIX)ROI$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)ROISUM$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCASUM$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN)ROI:EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN)ROI:TSNumPoints", "$(NCHANS)")

dbpf("$(PREFIX)MCA$(CHAN):ArrayData.LOPR", 0.5)
dbpf("$(PREFIX)C$(CHAN):DeadTime_RBV.SCAN", ".1 second")
dbpf("$(PREFIX)C$(CHAN):DTFactor_RBV.SCAN", ".1 second")

dbpf("$(PREFIX)MCA$(CHAN)ROI:1:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:2:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:3:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:4:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:5:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:6:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:7:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:8:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:9:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:10:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:11:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:12:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:13:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:14:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:15:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:16:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:17:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:18:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:19:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:20:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:21:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:22:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:23:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:24:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:25:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:26:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:27:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:28:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:29:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:30:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:31:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:32:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:33:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:34:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:35:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:36:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:37:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:38:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:39:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:40:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:41:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:42:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:43:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:44:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:45:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:46:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:47:Use", "Yes")
dbpf("$(PREFIX)MCA$(CHAN)ROI:48:Use", "Yes")
