# This file was automatically generated on Fri 04 Mar 2016 13:25:47 GMT from
# source: /home/vxn01537/xspress3/etc/makeIocs/example6Channel.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "/home/xspress3/software/epics/R3.14.12.3/support/xspress3-1-11-stu2/iocs/example6Channel"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '6000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "/home/xspress3/software/epics/R3.14.12.3/support/xspress3-1-11-stu2/iocs/example6Channel"

dbLoadDatabase "dbd/example6Channel.dbd"
example6Channel_registerRecordDeviceDriver(pdbbase)

callbackSetQueueSize(4000)


##################################################
# Start Xspress3 driver

# Parameters
# portName The Asyn port name to use
# numChannels The max number of channels (eg. 8)
# numCards The number of Xspress3 systems (normally 1)
# baseIP The base address used by the Xspress3 1Gig and 10Gig interfaces (eg. "192.168.0.1")
# Max Frames Used for XSPRESS3 API Configuration (depends on Xspress3 firmware config).
# Max Driver Frames Used to limit how big EPICS driver arrays are). Needs to match database MAX_FRAMES_DRIVER_RBV.
# maxSpectra The maximum size of each spectra (eg. 4096)
# maxBuffers Used by asynPortDriver (set to -1 for unlimited)
# maxMemory Used by asynPortDriver (set to -1 for unlimited)
# debug This debug flag is passed to xsp3_config in the Xspress API (0 or 1)
# simTest 0 or 1. Set to 1 to run up this driver in simulation mode. 
xspress3Config("XSP3", 6, 1, "192.168.0.1", 16384, 4096, 4096, 4096, 0, 0, 1 )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C1_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN1ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI1", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM1", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR1", 4096, 0, "XSP3.ROI1", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM1", 4096, 0, "XSP3.ROISUM1", 0, -1)

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C2_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN2ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI2", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM2", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR2", 4096, 0, "XSP3.ROI2", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM2", 4096, 0, "XSP3.ROISUM2", 0, -1)

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C3_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN3ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI3", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM3", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR3", 4096, 0, "XSP3.ROI3", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM3", 4096, 0, "XSP3.ROISUM3", 0, -1)

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C4_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN4ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI4", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM4", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR4", 4096, 0, "XSP3.ROI4", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM4", 4096, 0, "XSP3.ROISUM4", 0, -1)

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C5_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN5ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI5", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM5", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR5", 4096, 0, "XSP3.ROI5", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM5", 4096, 0, "XSP3.ROISUM5", 0, -1)

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA0", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA0" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_SCA7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6SCA7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI1", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI1" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI2", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI2" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI3", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI3" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI4", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI4" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI5", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI5" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI6", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI6" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI7", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI7" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI8", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI8" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI9", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI9" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI10", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI10" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI11", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI11" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI12", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI12" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI13", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI13" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI14", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI14" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI15", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI15" )

# NDAttrConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxTimeSeries, attrName)
NDAttrConfigure("XSP3.C6_ROI16", 4096, 0, "XSP3", 0,  -1, -1, 0,0, 4096, "CHAN6ROI16" )

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROI6", 4096, 0, "XSP3", 0, -1, -1)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROISUM6", 4096, 0, "XSP3.PROC", 0, -1, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARR6", 4096, 0, "XSP3.ROI6", 0, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("XSP3.ARRSUM6", 4096, 0, "XSP3.ROISUM6", 0, -1)

# NDProcessConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDProcessConfigure("XSP3.PROC", 16, 0, "XSP3", 0, 50, 0)

# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDROIConfigure("XSP3.ROIDATA", 16, 0, "XSP3", 0, 50, 0)

# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr)
NDFileHDF5Configure("XSP3.HDF5", 16, 0, "XSP3.ROIDATA", 0)

# Final ioc initialisation
# ------------------------
cd "/home/xspress3/software/epics/R3.14.12.3/support/xspress3-1-11-stu2/iocs/example6Channel"
dbLoadRecords(  'db/example6Channel_expanded.db', "XSPRESS3_PREFIX=XSPRESS3-EXAMPLE")
iocInit


#Set up some of the more complicated HDF PVs
dbpf("XSPRESS3-EXAMPLE:HDF5:FileTemplate", "%s%s%d.hdf5")
dbpf("XSPRESS3-EXAMPLE:HDF5:FileWriteMode", "Stream")
dbpf("XSPRESS3-EXAMPLE:HDF5:EnableCallbacks", "Enable")

#Set up the PROC plugin spectra summing
dbpf("XSPRESS3-EXAMPLE:PROC:EnableFilter", "Enable")
dbpf("XSPRESS3-EXAMPLE:PROC:FilterType", "Sum")
dbpf("XSPRESS3-EXAMPLE:PROC:EnableCallbacks", "Enable")

# Enable spectra for channel 1
dbpf("XSPRESS3-EXAMPLE:C1_PluginControlVal", "Enabled")

#Set up the ROI parameters
dbpf("XSPRESS3-EXAMPLE:ROIDATA:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROIDATA:EnableY", "Yes")

#Set the default energy and channel range for the ROIDATA plugin.
dbpf("XSPRESS3-EXAMPLE:ROIDATA:SizeX", "4096")
dbpf("XSPRESS3-EXAMPLE:ROIDATA:SizeY", "6")

# Xspress 3 configuration
dbpf("XSPRESS3-EXAMPLE:CONFIG_PATH", "/home/xspress3/software/epics/R3.14.12.3/support/xspress3-1-11-stu2/xspress3_settings/6channel")
dbpf("XSPRESS3-EXAMPLE:RUN_FLAGS","0")
dbpf("XSPRESS3-EXAMPLE:NUM_CHANNELS","6")
dbpf("XSPRESS3-EXAMPLE:NumImages", "100")

# hdf5 output
dbpf("XSPRESS3-EXAMPLE:HDF5:FilePath","/home/vxn01537/data")
dbpf("XSPRESS3-EXAMPLE:HDF5:FileName","test")
dbpf("XSPRESS3-EXAMPLE:ArrayCallbacks","Enable")
dbpf("XSPRESS3-EXAMPLE:ROIDATA:EnableCallbacks","Enable")

# connect to Xspress3
dbpf("XSPRESS3-EXAMPLE:CONNECT","1")

# set TTL trigger
dbpf("XSPRESS3-EXAMPLE:TriggerMode","TTL Veto Only")


dbpf("XSPRESS3-EXAMPLE:ROI1:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI1:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI1:MinY", "0")
dbpf("XSPRESS3-EXAMPLE:ROI1:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM1:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM1:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM1:MinY", "0")
dbpf("XSPRESS3-EXAMPLE:ROISUM1:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C1_PluginControlValExtraROI", "0")


dbpf("XSPRESS3-EXAMPLE:ROI2:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI2:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI2:MinY", "1")
dbpf("XSPRESS3-EXAMPLE:ROI2:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM2:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM2:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM2:MinY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM2:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C2_PluginControlValExtraROI", "0")

dbpf("XSPRESS3-EXAMPLE:C2_PluginControlVal", "0")

dbpf("XSPRESS3-EXAMPLE:ROI3:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI3:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI3:MinY", "2")
dbpf("XSPRESS3-EXAMPLE:ROI3:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM3:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM3:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM3:MinY", "2")
dbpf("XSPRESS3-EXAMPLE:ROISUM3:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C3_PluginControlValExtraROI", "0")

dbpf("XSPRESS3-EXAMPLE:C3_PluginControlVal", "0")

dbpf("XSPRESS3-EXAMPLE:ROI4:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI4:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI4:MinY", "3")
dbpf("XSPRESS3-EXAMPLE:ROI4:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM4:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM4:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM4:MinY", "3")
dbpf("XSPRESS3-EXAMPLE:ROISUM4:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C4_PluginControlValExtraROI", "0")

dbpf("XSPRESS3-EXAMPLE:C4_PluginControlVal", "0")

dbpf("XSPRESS3-EXAMPLE:ROI5:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI5:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI5:MinY", "4")
dbpf("XSPRESS3-EXAMPLE:ROI5:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM5:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM5:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM5:MinY", "4")
dbpf("XSPRESS3-EXAMPLE:ROISUM5:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C5_PluginControlValExtraROI", "0")

dbpf("XSPRESS3-EXAMPLE:C5_PluginControlVal", "0")

dbpf("XSPRESS3-EXAMPLE:ROI6:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI6:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROI6:MinY", "5")
dbpf("XSPRESS3-EXAMPLE:ROI6:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:ROISUM6:EnableX", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM6:EnableY", "Yes")
dbpf("XSPRESS3-EXAMPLE:ROISUM6:MinY", "5")
dbpf("XSPRESS3-EXAMPLE:ROISUM6:SizeY", "1")
dbpf("XSPRESS3-EXAMPLE:C6_PluginControlValExtraROI", "0")

dbpf("XSPRESS3-EXAMPLE:C6_PluginControlVal", "0")

dbpf XSPRESS3-EXAMPLE:NDAttributesFile, example6ChannelApp/data/XSP3.xml

















































































































































































































































































































































































