TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += st16Channel.sh
TARGETS += st16Channel.boot
TARGETS += st16ChannelMini.boot
include $(TOP)/configure/RULES.ioc
