TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += st8Channel.sh
TARGETS += st8Channel.boot
TARGETS += st8ChannelMini.boot
include $(TOP)/configure/RULES.ioc
