TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += st4Channel.sh
TARGETS += st4Channel.boot
TARGETS += st4ChannelMini.boot
include $(TOP)/configure/RULES.ioc
