TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================


INC += datamod.h
INC += xspress3.h
INC += xspress3_fem_api.h
INC += xspress3_dma_protocol.h
INC += os9types.h
INC += xspress3_data_mod.h

#LIB_INSTALLS_Linux += ../os/$(T_A)/libFemClient.a
LIB_INSTALLS_Linux += ../os/$(T_A)/libxspress3.a
LIB_INSTALLS_Linux += ../os/$(T_A)/libimg_mod.a
#LIB_INSTALLS_Linux += ../os/$(T_A)/libXspress3FemApi.a

#BIN_INSTALLS_Linux += ../os/$(T_A)/imgd
#BIN_INSTALLS_Linux += ../os/$(T_A)/xspress3test
#BIN_INSTALLS_Linux += ../os/$(T_A)/xspress3.server

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

