TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += st6Channel.sh
TARGETS += st6Channel.boot
TARGETS += st6ChannelMini.boot
include $(TOP)/configure/RULES.ioc
