/* This file was automatically generated on Mon 15 Dec 2014 18:37:16 GMT from
 * source: /home/npr78/diamond/support/xspress3/etc/makeIocs/example4Channel.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

