* dataTask
** wait for a stop event with a timeout
** wait for a start event
*** Do the arrays really need zeros written to them?
    Can the number of values written to the arrays be monitored so that old data is not passed.
** loop while acquiring
*** wait for a stop event with a timeout
*** If we have stopped, wait until we are not busy on all channels.
*** Read how many data frames have been transferred
#+BEGIN_SRC C++
  int getNumDataFramesTransferred()
  {
      int frameCount
      if (acquire || aborted) {
          xsp3_status = xsp3->scaler_check_progress(xsp3_handle_);
          if (xsp3_status < XSP3_OK) {
              checkStatus(xsp3_status, "xsp3_dma_check_desc", functionName);
              status = asynError;
          }
          frameCount = xsp3_status;
          setIntegerParam(xsp3FrameCountParam, frameCount-lastFrameCount);
          asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s frameCount: %d.\n", functionName, frameCount);
      } else {
          frameCount = 0;
      }
      return frameCount;
  }
#+END_SRC
* Questions
** What are the ROIs in the driver for?
** Are the number of channels defined by the hardware? 1-16?
** Is the HDF5 writer described in the templates just for the ROIs or raw data?
*** Where is it instantiated?
    It appears that this is not used in I18s as the HDF macro in highlevel is 'XSPRESS3-EXAMPLE:HDF5' and the ROIDATA NDFileHDF5 plugin has a P and R macro of 'BL18I-EA-XSP3-01:' and 'HDF5:' respectively
**** DONE Check the I18 UI PVs related to the HDF5 writer
     The UI looks at BL18I-EA-XSP3-01:HDF5:* so what is the point of the PVs in the highlevel template?
